version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_PORT: 9093
      KAFKA_ADVERTISED_LISTENER_PORT: 9093
      KAFKA_LISTENER_NAME: INSIDE_LISTENER
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE_LISTENER: INSIDE_LISTENER
      KAFKA_LISTENER_PORT_INSIDE_LISTENER: 9093
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper
